swagger: "2.0"
info:
  title: My API
  version: "1.0.0"
host: "${backend_address}"
schemes:
  - "http"
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "key"
    in: "query"
paths:
  /health:
    get:
      security:
        - api_key: []
      operationId: "getHealth"
      summary: Health check
      responses:
        200:
          description: OK
      x-google-backend:
        address: "http://${backend_address}"
        protocol: "http/1.1"