apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nodejs-ingress
  namespace: app
  annotations:
    kubernetes.io/ingress.class: "gce"
    # networking.gke.io/managed-certificates: "myapp-cert"
spec:
  # tls:
  #   - hosts:
  #     - myapp-supalongdnszzz.com
  #     secretName: myapp-tls
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sub-app1-svc
            port:
              number: 80