apiVersion: v1
kind: LimitRange
metadata:
  name: app-limit-range
  namespace: app
spec:
  limits:
  - type: Container
    default:
      cpu: "500m"
      memory: "500Mi"
    defaultRequest:
      cpu: "200m"
      memory: "128Mi"
    max:
      cpu: "1000m"
      memory: "1024Mi"
    min:
      cpu: "200m"
      memory: "128Mi"